# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/Rev2.0/UI/UI_Files/UI_Tags_Convert.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(685, 559)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_old_tag1 = QtWidgets.QLabel(Form)
        self.label_old_tag1.setObjectName("label_old_tag1")
        self.verticalLayout.addWidget(self.label_old_tag1)
        self.label_old_tag2 = QtWidgets.QLabel(Form)
        self.label_old_tag2.setObjectName("label_old_tag2")
        self.verticalLayout.addWidget(self.label_old_tag2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_old_tag1 = QtWidgets.QComboBox(Form)
        self.comboBox_old_tag1.setObjectName("comboBox_old_tag1")
        self.verticalLayout_2.addWidget(self.comboBox_old_tag1)
        self.comboBox_old_tag2 = QtWidgets.QComboBox(Form)
        self.comboBox_old_tag2.setObjectName("comboBox_old_tag2")
        self.verticalLayout_2.addWidget(self.comboBox_old_tag2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_new_tag1 = QtWidgets.QLabel(Form)
        self.label_new_tag1.setObjectName("label_new_tag1")
        self.verticalLayout_3.addWidget(self.label_new_tag1)
        self.label_new_tag2 = QtWidgets.QLabel(Form)
        self.label_new_tag2.setObjectName("label_new_tag2")
        self.verticalLayout_3.addWidget(self.label_new_tag2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_new_tag1 = QtWidgets.QComboBox(Form)
        self.comboBox_new_tag1.setObjectName("comboBox_new_tag1")
        self.verticalLayout_4.addWidget(self.comboBox_new_tag1)
        self.comboBox_new_tag2 = QtWidgets.QComboBox(Form)
        self.comboBox_new_tag2.setObjectName("comboBox_new_tag2")
        self.verticalLayout_4.addWidget(self.comboBox_new_tag2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_convert = QtWidgets.QPushButton(Form)
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.verticalLayout_5.addWidget(self.pushButton_convert)
        self.pushButton_cancel = QtWidgets.QPushButton(Form)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.verticalLayout_5.addWidget(self.pushButton_cancel)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_old_tag1.setText(_translate("Form", "Old Tag 1:"))
        self.label_old_tag2.setText(_translate("Form", "Old Tag 1:"))
        self.label_new_tag1.setText(_translate("Form", "New Tag 1:"))
        self.label_new_tag2.setText(_translate("Form", "New Tag 2:"))
        self.pushButton_convert.setText(_translate("Form", "Convert"))
        self.pushButton_cancel.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
