# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/ryank/Documents/Projects/XSavier/Rev2.9.1/XSavier/UI/UI_Files/UI_BillsAdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1143, 853)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_Fake = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Fake.setFont(font)
        self.label_Fake.setObjectName("label_Fake")
        self.gridLayout.addWidget(self.label_Fake, 2, 1, 1, 1)
        self.lineEdit_Amount = QtWidgets.QLineEdit(Form)
        self.lineEdit_Amount.setObjectName("lineEdit_Amount")
        self.gridLayout.addWidget(self.lineEdit_Amount, 3, 2, 1, 1)
        self.pushButton_Cancel = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Cancel.setFont(font)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.gridLayout.addWidget(self.pushButton_Cancel, 5, 0, 1, 4)
        self.label_Description = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Description.setFont(font)
        self.label_Description.setObjectName("label_Description")
        self.gridLayout.addWidget(self.label_Description, 1, 1, 1, 1)
        self.lineEdit_Description = QtWidgets.QLineEdit(Form)
        self.lineEdit_Description.setObjectName("lineEdit_Description")
        self.gridLayout.addWidget(self.lineEdit_Description, 1, 2, 1, 1)
        self.comboBox_PayFreq = QtWidgets.QComboBox(Form)
        self.comboBox_PayFreq.setObjectName("comboBox_PayFreq")
        self.gridLayout.addWidget(self.comboBox_PayFreq, 2, 2, 1, 1)
        self.label_BillName = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_BillName.setFont(font)
        self.label_BillName.setObjectName("label_BillName")
        self.gridLayout.addWidget(self.label_BillName, 0, 1, 1, 1)
        self.pushButton_Save = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.gridLayout.addWidget(self.pushButton_Save, 4, 0, 1, 4)
        self.lineEdit_BillName = QtWidgets.QLineEdit(Form)
        self.lineEdit_BillName.setObjectName("lineEdit_BillName")
        self.gridLayout.addWidget(self.lineEdit_BillName, 0, 2, 1, 1)
        self.label_Amount1 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_Amount1.setFont(font)
        self.label_Amount1.setObjectName("label_Amount1")
        self.gridLayout.addWidget(self.label_Amount1, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_Fake.setText(_translate("Form", "Pay Frequency:"))
        self.pushButton_Cancel.setText(_translate("Form", "Cancel"))
        self.label_Description.setText(_translate("Form", "Description:"))
        self.label_BillName.setText(_translate("Form", "Bill Name:"))
        self.pushButton_Save.setText(_translate("Form", "Save Bill"))
        self.label_Amount1.setText(_translate("Form", "Amount:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
