# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/UI_Files/UI_AddTag2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1025, 828)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_SaveTag = QtWidgets.QPushButton(Form)
        self.pushButton_SaveTag.setObjectName("pushButton_SaveTag")
        self.gridLayout.addWidget(self.pushButton_SaveTag, 2, 0, 1, 3)
        self.pushButton_Cancel = QtWidgets.QPushButton(Form)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.gridLayout.addWidget(self.pushButton_Cancel, 3, 0, 1, 3)
        self.label_Tag2Name = QtWidgets.QLabel(Form)
        self.label_Tag2Name.setObjectName("label_Tag2Name")
        self.gridLayout.addWidget(self.label_Tag2Name, 1, 0, 1, 1)
        self.lineEdit_Tag2Name = QtWidgets.QLineEdit(Form)
        self.lineEdit_Tag2Name.setObjectName("lineEdit_Tag2Name")
        self.gridLayout.addWidget(self.lineEdit_Tag2Name, 1, 1, 1, 2)
        self.label_Tie1Tag = QtWidgets.QLabel(Form)
        self.label_Tie1Tag.setObjectName("label_Tie1Tag")
        self.gridLayout.addWidget(self.label_Tie1Tag, 0, 0, 1, 1)
        self.comboBox_Tag1 = QtWidgets.QComboBox(Form)
        self.comboBox_Tag1.setObjectName("comboBox_Tag1")
        self.gridLayout.addWidget(self.comboBox_Tag1, 0, 1, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_SaveTag.setText(_translate("Form", "Save Tag"))
        self.pushButton_Cancel.setText(_translate("Form", "Cancel"))
        self.label_Tag2Name.setText(_translate("Form", "Tier 2 Tag Name:"))
        self.label_Tie1Tag.setText(_translate("Form", "Tier 1 Tag:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
