# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/Rev1.5/UI/UI_Files/UI_Import_Manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1145, 718)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_ImportManagerImage = QtWidgets.QLabel(Form)
        self.label_ImportManagerImage.setMaximumSize(QtCore.QSize(100, 100))
        self.label_ImportManagerImage.setText("")
        self.label_ImportManagerImage.setPixmap(QtGui.QPixmap(":/button_icons/button_icons/Import.ico"))
        self.label_ImportManagerImage.setScaledContents(True)
        self.label_ImportManagerImage.setObjectName("label_ImportManagerImage")
        self.horizontalLayout.addWidget(self.label_ImportManagerImage)
        self.label_ImportManager = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_ImportManager.setFont(font)
        self.label_ImportManager.setObjectName("label_ImportManager")
        self.horizontalLayout.addWidget(self.label_ImportManager)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("QPushButton{\n"
"    background-color:rgb(82, 157, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 4px;\n"
"    \n"
"    font: 87 12pt \"Arial Black\";\n"
"\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_Import = QtWidgets.QPushButton(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/button_icons/button_icons/Import.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Import.setIcon(icon)
        self.pushButton_Import.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Import.setObjectName("pushButton_Import")
        self.verticalLayout.addWidget(self.pushButton_Import)
        self.pushButton_SaveNote = QtWidgets.QPushButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/button_icons/button_icons/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_SaveNote.setIcon(icon1)
        self.pushButton_SaveNote.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_SaveNote.setObjectName("pushButton_SaveNote")
        self.verticalLayout.addWidget(self.pushButton_SaveNote)
        spacerItem1 = QtWidgets.QSpacerItem(20, 371, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_Home = QtWidgets.QPushButton(self.widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/button_icons/button_icons/Home.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Home.setIcon(icon2)
        self.pushButton_Home.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.verticalLayout.addWidget(self.pushButton_Home)
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.textEdit_ImportNotes = QtWidgets.QTextEdit(Form)
        self.textEdit_ImportNotes.setMaximumSize(QtCore.QSize(300, 100))
        self.textEdit_ImportNotes.setObjectName("textEdit_ImportNotes")
        self.horizontalLayout_2.addWidget(self.textEdit_ImportNotes)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.treeWidget_Imports = QtWidgets.QTreeWidget(Form)
        self.treeWidget_Imports.setObjectName("treeWidget_Imports")
        self.treeWidget_Imports.headerItem().setText(0, "1")
        self.verticalLayout_4.addWidget(self.treeWidget_Imports)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_ImportManager.setText(_translate("Form", "Import Manager"))
        self.pushButton_Import.setText(_translate("Form", "Import Data"))
        self.pushButton_SaveNote.setText(_translate("Form", "Save Note"))
        self.pushButton_Home.setText(_translate("Form", "Home"))
        self.label.setText(_translate("Form", "Import Notes:"))
import icons_resource_file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
