# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/Rev1.7/UI/UI_Files/UI_Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1031, 835)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_SettingsImage = QtWidgets.QLabel(Form)
        self.label_SettingsImage.setMaximumSize(QtCore.QSize(100, 100))
        self.label_SettingsImage.setText("")
        self.label_SettingsImage.setPixmap(QtGui.QPixmap(":/button_icons/button_icons/Settings.ico"))
        self.label_SettingsImage.setScaledContents(True)
        self.label_SettingsImage.setObjectName("label_SettingsImage")
        self.horizontalLayout_2.addWidget(self.label_SettingsImage)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("QPushButton{\n"
"\n"
"    background-color:rgb(82, 157, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 4px;\n"
"    \n"
"    font: 87 12pt \"Arial Black\";\n"
"\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_Tags = QtWidgets.QPushButton(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/button_icons/button_icons/tags.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Tags.setIcon(icon)
        self.pushButton_Tags.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Tags.setObjectName("pushButton_Tags")
        self.verticalLayout.addWidget(self.pushButton_Tags)
        self.pushButton_keywordTagging = QtWidgets.QPushButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/button_icons/button_icons/lock.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_keywordTagging.setIcon(icon1)
        self.pushButton_keywordTagging.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_keywordTagging.setObjectName("pushButton_keywordTagging")
        self.verticalLayout.addWidget(self.pushButton_keywordTagging)
        self.pushButton_ApplicationSettings = QtWidgets.QPushButton(self.widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/button_icons/button_icons/Settings.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ApplicationSettings.setIcon(icon2)
        self.pushButton_ApplicationSettings.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_ApplicationSettings.setObjectName("pushButton_ApplicationSettings")
        self.verticalLayout.addWidget(self.pushButton_ApplicationSettings)
        spacerItem1 = QtWidgets.QSpacerItem(20, 421, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_Home = QtWidgets.QPushButton(self.widget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/button_icons/button_icons/Home.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Home.setIcon(icon3)
        self.pushButton_Home.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.verticalLayout.addWidget(self.pushButton_Home)
        self.pushButton_DeveloperDetails = QtWidgets.QPushButton(self.widget)
        self.pushButton_DeveloperDetails.setStyleSheet("QPushButton{\n"
"\n"
"    \n"
"    background-color: rgb(226, 222, 89);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 4px;\n"
"    \n"
"    font: 87 12pt \"Arial Black\";\n"
"\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/button_icons/button_icons/devloper.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_DeveloperDetails.setIcon(icon4)
        self.pushButton_DeveloperDetails.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_DeveloperDetails.setObjectName("pushButton_DeveloperDetails")
        self.verticalLayout.addWidget(self.pushButton_DeveloperDetails)
        self.verticalLayout_3.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Settings"))
        self.pushButton_Tags.setText(_translate("Form", "Tags"))
        self.pushButton_keywordTagging.setText(_translate("Form", "Key Word Tagging"))
        self.pushButton_ApplicationSettings.setText(_translate("Form", "App Settings"))
        self.pushButton_Home.setText(_translate("Form", "Home"))
        self.pushButton_DeveloperDetails.setText(_translate("Form", "Devloper Details"))
import icons_resource_file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
