# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/UI_Files/UI_NewAccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(739, 525)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_AccountTypes = QtWidgets.QComboBox(Form)
        self.comboBox_AccountTypes.setObjectName("comboBox_AccountTypes")
        self.comboBox_AccountTypes.addItem("")
        self.comboBox_AccountTypes.addItem("")
        self.comboBox_AccountTypes.addItem("")
        self.comboBox_AccountTypes.addItem("")
        self.comboBox_AccountTypes.addItem("")
        self.gridLayout.addWidget(self.comboBox_AccountTypes, 1, 1, 1, 1)
        self.label_AccountName = QtWidgets.QLabel(Form)
        self.label_AccountName.setObjectName("label_AccountName")
        self.gridLayout.addWidget(self.label_AccountName, 0, 0, 1, 1)
        self.pushButton_Submit = QtWidgets.QPushButton(Form)
        self.pushButton_Submit.setObjectName("pushButton_Submit")
        self.gridLayout.addWidget(self.pushButton_Submit, 2, 0, 1, 2)
        self.label_AccountType = QtWidgets.QLabel(Form)
        self.label_AccountType.setObjectName("label_AccountType")
        self.gridLayout.addWidget(self.label_AccountType, 1, 0, 1, 1)
        self.lineEdit_AccountName = QtWidgets.QLineEdit(Form)
        self.lineEdit_AccountName.setObjectName("lineEdit_AccountName")
        self.gridLayout.addWidget(self.lineEdit_AccountName, 0, 1, 1, 1)
        self.pushButton_Cancel = QtWidgets.QPushButton(Form)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.gridLayout.addWidget(self.pushButton_Cancel, 3, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox_AccountTypes.setItemText(0, _translate("Form", "Credit Card"))
        self.comboBox_AccountTypes.setItemText(1, _translate("Form", "Debt"))
        self.comboBox_AccountTypes.setItemText(2, _translate("Form", "Investment"))
        self.comboBox_AccountTypes.setItemText(3, _translate("Form", "Bank"))
        self.comboBox_AccountTypes.setItemText(4, _translate("Form", "Other"))
        self.label_AccountName.setText(_translate("Form", "Account Name:"))
        self.pushButton_Submit.setText(_translate("Form", "Submit"))
        self.label_AccountType.setText(_translate("Form", "Account Type:"))
        self.pushButton_Cancel.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
