# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/UI_Files/UI_EditTag1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1025, 368)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_CalcDisabled = QtWidgets.QRadioButton(Form)
        self.radioButton_CalcDisabled.setAutoExclusive(False)
        self.radioButton_CalcDisabled.setObjectName("radioButton_CalcDisabled")
        self.gridLayout.addWidget(self.radioButton_CalcDisabled, 5, 2, 1, 2)
        self.lineEdit_TagName = QtWidgets.QLineEdit(Form)
        self.lineEdit_TagName.setObjectName("lineEdit_TagName")
        self.gridLayout.addWidget(self.lineEdit_TagName, 1, 1, 1, 3)
        self.label_ColorLabel = QtWidgets.QLabel(Form)
        self.label_ColorLabel.setObjectName("label_ColorLabel")
        self.gridLayout.addWidget(self.label_ColorLabel, 3, 0, 1, 1)
        self.lineEdit_Budget = QtWidgets.QLineEdit(Form)
        self.lineEdit_Budget.setObjectName("lineEdit_Budget")
        self.gridLayout.addWidget(self.lineEdit_Budget, 2, 1, 1, 3)
        self.radioButton_VisibleEnabled = QtWidgets.QRadioButton(Form)
        self.radioButton_VisibleEnabled.setAutoExclusive(False)
        self.radioButton_VisibleEnabled.setObjectName("radioButton_VisibleEnabled")
        self.gridLayout.addWidget(self.radioButton_VisibleEnabled, 4, 0, 1, 2)
        self.radioButton_VisibleDisabled = QtWidgets.QRadioButton(Form)
        self.radioButton_VisibleDisabled.setObjectName("radioButton_VisibleDisabled")
        self.gridLayout.addWidget(self.radioButton_VisibleDisabled, 4, 2, 1, 2)
        self.label_ColorCode = QtWidgets.QLabel(Form)
        self.label_ColorCode.setObjectName("label_ColorCode")
        self.gridLayout.addWidget(self.label_ColorCode, 3, 1, 1, 1)
        self.pushButton_ColorPicker = QtWidgets.QPushButton(Form)
        self.pushButton_ColorPicker.setObjectName("pushButton_ColorPicker")
        self.gridLayout.addWidget(self.pushButton_ColorPicker, 3, 2, 1, 2)
        self.label_TagName = QtWidgets.QLabel(Form)
        self.label_TagName.setObjectName("label_TagName")
        self.gridLayout.addWidget(self.label_TagName, 1, 0, 1, 1)
        self.radioButton_CalcEnabled = QtWidgets.QRadioButton(Form)
        self.radioButton_CalcEnabled.setAutoExclusive(False)
        self.radioButton_CalcEnabled.setObjectName("radioButton_CalcEnabled")
        self.gridLayout.addWidget(self.radioButton_CalcEnabled, 5, 0, 1, 2)
        self.pushButton_SaveTag = QtWidgets.QPushButton(Form)
        self.pushButton_SaveTag.setObjectName("pushButton_SaveTag")
        self.gridLayout.addWidget(self.pushButton_SaveTag, 7, 0, 1, 4)
        self.pushButton_Cancel = QtWidgets.QPushButton(Form)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.gridLayout.addWidget(self.pushButton_Cancel, 8, 0, 1, 4)
        self.label_TagID = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_TagID.sizePolicy().hasHeightForWidth())
        self.label_TagID.setSizePolicy(sizePolicy)
        self.label_TagID.setObjectName("label_TagID")
        self.gridLayout.addWidget(self.label_TagID, 0, 0, 1, 1)
        self.label_TagID_Value = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_TagID_Value.sizePolicy().hasHeightForWidth())
        self.label_TagID_Value.setSizePolicy(sizePolicy)
        self.label_TagID_Value.setObjectName("label_TagID_Value")
        self.gridLayout.addWidget(self.label_TagID_Value, 0, 1, 1, 3)
        self.label_Budget = QtWidgets.QLabel(Form)
        self.label_Budget.setObjectName("label_Budget")
        self.gridLayout.addWidget(self.label_Budget, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.radioButton_CalcDisabled.setText(_translate("Form", "Don\'t Use In Calculations"))
        self.label_ColorLabel.setText(_translate("Form", "Color Code:"))
        self.radioButton_VisibleEnabled.setText(_translate("Form", "Enabled"))
        self.radioButton_VisibleDisabled.setText(_translate("Form", "Disbaled"))
        self.label_ColorCode.setText(_translate("Form", "Color"))
        self.pushButton_ColorPicker.setText(_translate("Form", "Update Color"))
        self.label_TagName.setText(_translate("Form", "Tag:"))
        self.radioButton_CalcEnabled.setText(_translate("Form", "Use In Calculations"))
        self.pushButton_SaveTag.setText(_translate("Form", "Save Tag"))
        self.pushButton_Cancel.setText(_translate("Form", "Cancel"))
        self.label_TagID.setText(_translate("Form", "Tag ID:"))
        self.label_TagID_Value.setText(_translate("Form", "ID HERE"))
        self.label_Budget.setText(_translate("Form", "Budget:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
