# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/Rev1.7/UI/UI_Files/UI_KeywordTagging.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(902, 735)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_addRule = QtWidgets.QPushButton(Form)
        self.pushButton_addRule.setObjectName("pushButton_addRule")
        self.horizontalLayout.addWidget(self.pushButton_addRule)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_editeRule = QtWidgets.QPushButton(Form)
        self.pushButton_editeRule.setObjectName("pushButton_editeRule")
        self.horizontalLayout_2.addWidget(self.pushButton_editeRule)
        self.comboBox_editRule = QtWidgets.QComboBox(Form)
        self.comboBox_editRule.setObjectName("comboBox_editRule")
        self.horizontalLayout_2.addWidget(self.comboBox_editRule)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.pushButton_home = QtWidgets.QPushButton(Form)
        self.pushButton_home.setObjectName("pushButton_home")
        self.verticalLayout_2.addWidget(self.pushButton_home)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.tableWidget_rules = QtWidgets.QTableWidget(Form)
        self.tableWidget_rules.setObjectName("tableWidget_rules")
        self.tableWidget_rules.setColumnCount(0)
        self.tableWidget_rules.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.tableWidget_rules)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Key Word Rules"))
        self.pushButton_addRule.setText(_translate("Form", "Add Rule"))
        self.pushButton_editeRule.setText(_translate("Form", "Edit Rule"))
        self.pushButton_home.setText(_translate("Form", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
