# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/Rev2.0/UI/UI_Files/UI_Tags.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(998, 903)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_DeleteTag1 = QtWidgets.QPushButton(Form)
        self.pushButton_DeleteTag1.setObjectName("pushButton_DeleteTag1")
        self.gridLayout.addWidget(self.pushButton_DeleteTag1, 4, 0, 1, 2)
        self.comboBox_EditTag1 = QtWidgets.QComboBox(Form)
        self.comboBox_EditTag1.setObjectName("comboBox_EditTag1")
        self.gridLayout.addWidget(self.comboBox_EditTag1, 0, 1, 1, 1)
        self.pushButton_AddTag2 = QtWidgets.QPushButton(Form)
        self.pushButton_AddTag2.setObjectName("pushButton_AddTag2")
        self.gridLayout.addWidget(self.pushButton_AddTag2, 2, 0, 1, 2)
        self.pushButton_AddTag1 = QtWidgets.QPushButton(Form)
        self.pushButton_AddTag1.setObjectName("pushButton_AddTag1")
        self.gridLayout.addWidget(self.pushButton_AddTag1, 1, 0, 1, 2)
        self.pushButton_Edit_Tag1 = QtWidgets.QPushButton(Form)
        self.pushButton_Edit_Tag1.setObjectName("pushButton_Edit_Tag1")
        self.gridLayout.addWidget(self.pushButton_Edit_Tag1, 0, 0, 1, 1)
        self.pushButton_Home = QtWidgets.QPushButton(Form)
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.gridLayout.addWidget(self.pushButton_Home, 6, 0, 1, 3)
        self.pushButton_DeleteTag2 = QtWidgets.QPushButton(Form)
        self.pushButton_DeleteTag2.setObjectName("pushButton_DeleteTag2")
        self.gridLayout.addWidget(self.pushButton_DeleteTag2, 5, 0, 1, 2)
        self.treeWidget_Tags = QtWidgets.QTreeWidget(Form)
        self.treeWidget_Tags.setObjectName("treeWidget_Tags")
        self.treeWidget_Tags.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.treeWidget_Tags, 0, 2, 6, 1)
        self.pushButton_convert_tags = QtWidgets.QPushButton(Form)
        self.pushButton_convert_tags.setObjectName("pushButton_convert_tags")
        self.gridLayout.addWidget(self.pushButton_convert_tags, 3, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_DeleteTag1.setText(_translate("Form", "Delete Tag 1"))
        self.pushButton_AddTag2.setText(_translate("Form", "Add Tag 2"))
        self.pushButton_AddTag1.setText(_translate("Form", "Add Tag 1"))
        self.pushButton_Edit_Tag1.setText(_translate("Form", "Edit Tag 1"))
        self.pushButton_Home.setText(_translate("Form", "Home"))
        self.pushButton_DeleteTag2.setText(_translate("Form", "Delete Tag 2"))
        self.pushButton_convert_tags.setText(_translate("Form", "Convert Tags"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
