# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/Rev2.0/UI/UI_Files/UI_Accounts_Config.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(886, 690)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_Amount2Col = QtWidgets.QComboBox(Form)
        self.comboBox_Amount2Col.setObjectName("comboBox_Amount2Col")
        self.gridLayout.addWidget(self.comboBox_Amount2Col, 5, 2, 1, 1)
        self.label_Sign1 = QtWidgets.QLabel(Form)
        self.label_Sign1.setObjectName("label_Sign1")
        self.gridLayout.addWidget(self.label_Sign1, 4, 3, 1, 1)
        self.comboBox_Sign2 = QtWidgets.QComboBox(Form)
        self.comboBox_Sign2.setObjectName("comboBox_Sign2")
        self.gridLayout.addWidget(self.comboBox_Sign2, 5, 4, 1, 1)
        self.comboBox_PostedDateCol = QtWidgets.QComboBox(Form)
        self.comboBox_PostedDateCol.setObjectName("comboBox_PostedDateCol")
        self.gridLayout.addWidget(self.comboBox_PostedDateCol, 2, 2, 1, 1)
        self.label_PostedDate = QtWidgets.QLabel(Form)
        self.label_PostedDate.setObjectName("label_PostedDate")
        self.gridLayout.addWidget(self.label_PostedDate, 2, 1, 1, 1)
        self.label_Description = QtWidgets.QLabel(Form)
        self.label_Description.setObjectName("label_Description")
        self.gridLayout.addWidget(self.label_Description, 3, 1, 1, 1)
        self.comboBox_Amount1Col = QtWidgets.QComboBox(Form)
        self.comboBox_Amount1Col.setObjectName("comboBox_Amount1Col")
        self.gridLayout.addWidget(self.comboBox_Amount1Col, 4, 2, 1, 1)
        self.pushButton_Cancel = QtWidgets.QPushButton(Form)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.gridLayout.addWidget(self.pushButton_Cancel, 4, 0, 1, 1)
        self.comboBox_Accounts = QtWidgets.QComboBox(Form)
        self.comboBox_Accounts.setObjectName("comboBox_Accounts")
        self.gridLayout.addWidget(self.comboBox_Accounts, 0, 0, 1, 5)
        self.pushButton_Config = QtWidgets.QPushButton(Form)
        self.pushButton_Config.setObjectName("pushButton_Config")
        self.gridLayout.addWidget(self.pushButton_Config, 3, 0, 1, 1)
        self.comboBox_Sign1 = QtWidgets.QComboBox(Form)
        self.comboBox_Sign1.setObjectName("comboBox_Sign1")
        self.gridLayout.addWidget(self.comboBox_Sign1, 4, 4, 1, 1)
        self.pushButton_Save = QtWidgets.QPushButton(Form)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.gridLayout.addWidget(self.pushButton_Save, 6, 0, 1, 5)
        self.label_Amount2 = QtWidgets.QLabel(Form)
        self.label_Amount2.setObjectName("label_Amount2")
        self.gridLayout.addWidget(self.label_Amount2, 5, 1, 1, 1)
        self.label_Amount1 = QtWidgets.QLabel(Form)
        self.label_Amount1.setObjectName("label_Amount1")
        self.gridLayout.addWidget(self.label_Amount1, 4, 1, 1, 1)
        self.label_Sign2 = QtWidgets.QLabel(Form)
        self.label_Sign2.setObjectName("label_Sign2")
        self.gridLayout.addWidget(self.label_Sign2, 5, 3, 1, 1)
        self.pushButton_Cancel_Config = QtWidgets.QPushButton(Form)
        self.pushButton_Cancel_Config.setObjectName("pushButton_Cancel_Config")
        self.gridLayout.addWidget(self.pushButton_Cancel_Config, 7, 0, 1, 5)
        self.comboBox_DescriptionCol = QtWidgets.QComboBox(Form)
        self.comboBox_DescriptionCol.setObjectName("comboBox_DescriptionCol")
        self.gridLayout.addWidget(self.comboBox_DescriptionCol, 3, 2, 1, 1)
        self.label_TransDate = QtWidgets.QLabel(Form)
        self.label_TransDate.setObjectName("label_TransDate")
        self.gridLayout.addWidget(self.label_TransDate, 1, 1, 1, 1)
        self.comboBox_TransDateCol = QtWidgets.QComboBox(Form)
        self.comboBox_TransDateCol.setObjectName("comboBox_TransDateCol")
        self.gridLayout.addWidget(self.comboBox_TransDateCol, 1, 2, 1, 1)
        self.label_Account = QtWidgets.QLabel(Form)
        self.label_Account.setObjectName("label_Account")
        self.gridLayout.addWidget(self.label_Account, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_Sign1.setText(_translate("Form", "Sign:"))
        self.label_PostedDate.setText(_translate("Form", "Posted Date Column:"))
        self.label_Description.setText(_translate("Form", "Description Column:"))
        self.pushButton_Cancel.setText(_translate("Form", "Cancel"))
        self.pushButton_Config.setText(_translate("Form", "Configure Import"))
        self.pushButton_Save.setText(_translate("Form", "Save Settings"))
        self.label_Amount2.setText(_translate("Form", "Amount 2 Column:"))
        self.label_Amount1.setText(_translate("Form", "Amount 1 Column:"))
        self.label_Sign2.setText(_translate("Form", "Sign:"))
        self.pushButton_Cancel_Config.setText(_translate("Form", "Cancel"))
        self.label_TransDate.setText(_translate("Form", "Transaction Date Column:"))
        self.label_Account.setText(_translate("Form", "Account Name Here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
