# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/Rev1/UI/UI_Files/UI_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuDatabase = QtWidgets.QMenu(self.menuTools)
        self.menuDatabase.setObjectName("menuDatabase")
        self.menuFiles = QtWidgets.QMenu(self.menuTools)
        self.menuFiles.setObjectName("menuFiles")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRestore_database = QtWidgets.QAction(MainWindow)
        self.actionRestore_database.setObjectName("actionRestore_database")
        self.actionBackup_Database = QtWidgets.QAction(MainWindow)
        self.actionBackup_Database.setObjectName("actionBackup_Database")
        self.actionRestore_Database = QtWidgets.QAction(MainWindow)
        self.actionRestore_Database.setObjectName("actionRestore_Database")
        self.actionPush_Database_Update = QtWidgets.QAction(MainWindow)
        self.actionPush_Database_Update.setObjectName("actionPush_Database_Update")
        self.actionImport_Files = QtWidgets.QAction(MainWindow)
        self.actionImport_Files.setObjectName("actionImport_Files")
        self.menuDatabase.addAction(self.actionBackup_Database)
        self.menuDatabase.addAction(self.actionRestore_Database)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.actionPush_Database_Update)
        self.menuFiles.addAction(self.actionImport_Files)
        self.menuTools.addAction(self.menuDatabase.menuAction())
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.menuFiles.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuDatabase.setTitle(_translate("MainWindow", "Database"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.actionRestore_database.setText(_translate("MainWindow", "Restore database"))
        self.actionBackup_Database.setText(_translate("MainWindow", "Backup Database"))
        self.actionRestore_Database.setText(_translate("MainWindow", "Restore Database"))
        self.actionPush_Database_Update.setText(_translate("MainWindow", "Push Database Update"))
        self.actionImport_Files.setText(_translate("MainWindow", "Import Files"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
