# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/Rev1.3/UI/UI_Files/UI_SplashScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1038, 418)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_XSavierLogo = QtWidgets.QLabel(Form)
        self.label_XSavierLogo.setMaximumSize(QtCore.QSize(100, 100))
        self.label_XSavierLogo.setText("")
        self.label_XSavierLogo.setPixmap(QtGui.QPixmap("C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/Rev1.3/UI/UI_Files\\../../images/logo.jpg"))
        self.label_XSavierLogo.setScaledContents(True)
        self.label_XSavierLogo.setObjectName("label_XSavierLogo")
        self.horizontalLayout.addWidget(self.label_XSavierLogo)
        self.label_XSavierLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_XSavierLabel.setFont(font)
        self.label_XSavierLabel.setObjectName("label_XSavierLabel")
        self.horizontalLayout.addWidget(self.label_XSavierLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_XSavierLabel.setText(_translate("Form", "XSavier"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
