# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/Rev1/UI/UI_Files/UI_MoveFiles.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(904, 876)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_DropFiles = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_DropFiles.setFont(font)
        self.label_DropFiles.setObjectName("label_DropFiles")
        self.gridLayout.addWidget(self.label_DropFiles, 0, 0, 1, 1)
        self.pushButton_MoveFiles = QtWidgets.QPushButton(Form)
        self.pushButton_MoveFiles.setObjectName("pushButton_MoveFiles")
        self.gridLayout.addWidget(self.pushButton_MoveFiles, 4, 0, 1, 1)
        self.tableWidget_files = QtWidgets.QTableWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tableWidget_files.setFont(font)
        self.tableWidget_files.setObjectName("tableWidget_files")
        self.tableWidget_files.setColumnCount(0)
        self.tableWidget_files.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_files, 3, 0, 1, 1)
        self.pushButton_MoveToTable = QtWidgets.QPushButton(Form)
        self.pushButton_MoveToTable.setObjectName("pushButton_MoveToTable")
        self.gridLayout.addWidget(self.pushButton_MoveToTable, 2, 0, 1, 1)
        self.pushButton_Home = QtWidgets.QPushButton(Form)
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.gridLayout.addWidget(self.pushButton_Home, 5, 0, 1, 1)
        self.listWidget_DropFiles = QtWidgets.QListWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.listWidget_DropFiles.setFont(font)
        self.listWidget_DropFiles.setObjectName("listWidget_DropFiles")
        self.gridLayout.addWidget(self.listWidget_DropFiles, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_DropFiles.setText(_translate("Form", "Drop Files Below"))
        self.pushButton_MoveFiles.setText(_translate("Form", "Move Files"))
        self.pushButton_MoveToTable.setText(_translate("Form", "Moved to Table"))
        self.pushButton_Home.setText(_translate("Form", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
