# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/Rev1.7/UI/UI_Files/UI_EditKeywordRule.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(883, 670)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_4.addWidget(self.label_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_id_label = QtWidgets.QLabel(Form)
        self.label_id_label.setObjectName("label_id_label")
        self.horizontalLayout_5.addWidget(self.label_id_label)
        self.label_id = QtWidgets.QLabel(Form)
        self.label_id.setObjectName("label_id")
        self.horizontalLayout_5.addWidget(self.label_id)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_key = QtWidgets.QLabel(Form)
        self.label_key.setObjectName("label_key")
        self.horizontalLayout_3.addWidget(self.label_key)
        self.lineEdit_key = QtWidgets.QLineEdit(Form)
        self.lineEdit_key.setObjectName("lineEdit_key")
        self.horizontalLayout_3.addWidget(self.lineEdit_key)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_tag1 = QtWidgets.QLabel(Form)
        self.label_tag1.setObjectName("label_tag1")
        self.horizontalLayout_2.addWidget(self.label_tag1)
        self.comboBox_tag1 = QtWidgets.QComboBox(Form)
        self.comboBox_tag1.setObjectName("comboBox_tag1")
        self.horizontalLayout_2.addWidget(self.comboBox_tag1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_tag2 = QtWidgets.QLabel(Form)
        self.label_tag2.setObjectName("label_tag2")
        self.horizontalLayout.addWidget(self.label_tag2)
        self.comboBox_tag2 = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_tag2.sizePolicy().hasHeightForWidth())
        self.comboBox_tag2.setSizePolicy(sizePolicy)
        self.comboBox_tag2.setObjectName("comboBox_tag2")
        self.horizontalLayout.addWidget(self.comboBox_tag2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_update = QtWidgets.QPushButton(Form)
        self.pushButton_update.setObjectName("pushButton_update")
        self.verticalLayout.addWidget(self.pushButton_update)
        self.pushButton_deleteRule = QtWidgets.QPushButton(Form)
        self.pushButton_deleteRule.setObjectName("pushButton_deleteRule")
        self.verticalLayout.addWidget(self.pushButton_deleteRule)
        self.pushButton_cancel = QtWidgets.QPushButton(Form)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.verticalLayout.addWidget(self.pushButton_cancel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_title.setText(_translate("Form", "Edit Rule"))
        self.label_id_label.setText(_translate("Form", "ID:"))
        self.label_id.setText(_translate("Form", "TextLabel"))
        self.label_key.setText(_translate("Form", "Key:"))
        self.label_tag1.setText(_translate("Form", "Tag 1:"))
        self.label_tag2.setText(_translate("Form", "Tag 2:"))
        self.pushButton_update.setText(_translate("Form", "Update"))
        self.pushButton_deleteRule.setText(_translate("Form", "Delete Rule"))
        self.pushButton_cancel.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
