# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/Rev2.0/UI/UI_Files/UI_Application_Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(907, 782)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("QPushButton{\n"
"\n"
"    background-color:rgb(82, 157, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 4px;\n"
"    \n"
"    font: 87 12pt \"Arial Black\";\n"
"\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_UpdateSettings = QtWidgets.QPushButton(self.widget)
        self.pushButton_UpdateSettings.setObjectName("pushButton_UpdateSettings")
        self.verticalLayout.addWidget(self.pushButton_UpdateSettings)
        self.pushButton_Settings = QtWidgets.QPushButton(self.widget)
        self.pushButton_Settings.setObjectName("pushButton_Settings")
        self.verticalLayout.addWidget(self.pushButton_Settings)
        spacerItem = QtWidgets.QSpacerItem(20, 641, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.widget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_StartUpProcess = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_StartUpProcess.setFont(font)
        self.label_StartUpProcess.setObjectName("label_StartUpProcess")
        self.horizontalLayout.addWidget(self.label_StartUpProcess)
        self.comboBox_StartUpProcess = QtWidgets.QComboBox(Form)
        self.comboBox_StartUpProcess.setObjectName("comboBox_StartUpProcess")
        self.comboBox_StartUpProcess.addItem("")
        self.comboBox_StartUpProcess.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_StartUpProcess)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_BarChartZeros = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_BarChartZeros.setFont(font)
        self.label_BarChartZeros.setObjectName("label_BarChartZeros")
        self.horizontalLayout_2.addWidget(self.label_BarChartZeros)
        self.comboBox_BarChartZeros = QtWidgets.QComboBox(Form)
        self.comboBox_BarChartZeros.setObjectName("comboBox_BarChartZeros")
        self.comboBox_BarChartZeros.addItem("")
        self.comboBox_BarChartZeros.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_BarChartZeros)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_UpdateSettings.setText(_translate("Form", "Update Settings"))
        self.pushButton_Settings.setText(_translate("Form", "Settings"))
        self.label_StartUpProcess.setText(_translate("Form", "Start Up Process:"))
        self.comboBox_StartUpProcess.setItemText(0, _translate("Form", "Enabled"))
        self.comboBox_StartUpProcess.setItemText(1, _translate("Form", "Disabled"))
        self.label_BarChartZeros.setText(_translate("Form", "Bar Chart - Show Zeros:"))
        self.comboBox_BarChartZeros.setItemText(0, _translate("Form", "Enabled"))
        self.comboBox_BarChartZeros.setItemText(1, _translate("Form", "Disabled"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
