# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/Rev1.5/UI/UI_Files/UI_DeveloperDetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1006, 885)
        Form.setStyleSheet("")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_DeveloperIcon = QtWidgets.QLabel(self.widget)
        self.label_DeveloperIcon.setMaximumSize(QtCore.QSize(100, 100))
        self.label_DeveloperIcon.setText("")
        self.label_DeveloperIcon.setPixmap(QtGui.QPixmap(":/button_icons/button_icons/devloper.ico"))
        self.label_DeveloperIcon.setScaledContents(True)
        self.label_DeveloperIcon.setObjectName("label_DeveloperIcon")
        self.horizontalLayout.addWidget(self.label_DeveloperIcon)
        self.label_DevloperDetails = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_DevloperDetails.setFont(font)
        self.label_DevloperDetails.setObjectName("label_DevloperDetails")
        self.horizontalLayout.addWidget(self.label_DevloperDetails)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_DeveloperLogo = QtWidgets.QLabel(self.widget)
        self.label_DeveloperLogo.setMinimumSize(QtCore.QSize(0, 0))
        self.label_DeveloperLogo.setMaximumSize(QtCore.QSize(400, 500))
        self.label_DeveloperLogo.setText("")
        self.label_DeveloperLogo.setPixmap(QtGui.QPixmap(":/Other_Icons/Devloper_Logo.png"))
        self.label_DeveloperLogo.setScaledContents(True)
        self.label_DeveloperLogo.setObjectName("label_DeveloperLogo")
        self.horizontalLayout_2.addWidget(self.label_DeveloperLogo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_DeveloperCompany_1 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_DeveloperCompany_1.setFont(font)
        self.label_DeveloperCompany_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_DeveloperCompany_1.setObjectName("label_DeveloperCompany_1")
        self.horizontalLayout_4.addWidget(self.label_DeveloperCompany_1)
        self.label__DeveloperCompany_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label__DeveloperCompany_2.setFont(font)
        self.label__DeveloperCompany_2.setObjectName("label__DeveloperCompany_2")
        self.horizontalLayout_4.addWidget(self.label__DeveloperCompany_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.label_DeveloperLanguage_1 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_DeveloperLanguage_1.setFont(font)
        self.label_DeveloperLanguage_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_DeveloperLanguage_1.setObjectName("label_DeveloperLanguage_1")
        self.horizontalLayout_3.addWidget(self.label_DeveloperLanguage_1)
        self.label__DeveloperLanguage_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label__DeveloperLanguage_2.setFont(font)
        self.label__DeveloperLanguage_2.setObjectName("label__DeveloperLanguage_2")
        self.horizontalLayout_3.addWidget(self.label__DeveloperLanguage_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.pushButton_Settings = QtWidgets.QPushButton(self.widget)
        self.pushButton_Settings.setStyleSheet("QPushButton{\n"
"\n"
"    background-color:rgb(82, 157, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 4px;\n"
"    \n"
"    font: 87 12pt \"Arial Black\";\n"
"\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/button_icons/button_icons/Settings.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Settings.setIcon(icon)
        self.pushButton_Settings.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Settings.setObjectName("pushButton_Settings")
        self.verticalLayout_3.addWidget(self.pushButton_Settings)
        self.verticalLayout_4.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_DevloperDetails.setText(_translate("Form", "Developer Details"))
        self.label_DeveloperCompany_1.setText(_translate("Form", "Devloper:"))
        self.label__DeveloperCompany_2.setText(_translate("Form", "Ryan Programming (Super Real Company)"))
        self.label_DeveloperLanguage_1.setText(_translate("Form", "Devloper Language:"))
        self.label__DeveloperLanguage_2.setText(_translate("Form", "Python"))
        self.pushButton_Settings.setText(_translate("Form", "Settings"))
import icons_resource_file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
