# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/admin/Documents/Coding_Python/Budget_App/Rev_3_Import_CSV/Rev1.5/UI/UI_Files/UI_Accounts.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1027, 647)
        Form.setStyleSheet("")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelAccountsImage = QtWidgets.QLabel(Form)
        self.labelAccountsImage.setText("")
        self.labelAccountsImage.setPixmap(QtGui.QPixmap(":/button_icons/button_icons/Accounts.ico"))
        self.labelAccountsImage.setObjectName("labelAccountsImage")
        self.horizontalLayout.addWidget(self.labelAccountsImage)
        self.label_Accounts = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_Accounts.setFont(font)
        self.label_Accounts.setObjectName("label_Accounts")
        self.horizontalLayout.addWidget(self.label_Accounts)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("QPushButton{\n"
"    background-color:rgb(82, 157, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"    padding: 4px;\n"
"    \n"
"    font: 87 12pt \"Arial Black\";\n"
"\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_NewAccount = QtWidgets.QPushButton(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/button_icons/button_icons/plus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_NewAccount.setIcon(icon)
        self.pushButton_NewAccount.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_NewAccount.setObjectName("pushButton_NewAccount")
        self.verticalLayout.addWidget(self.pushButton_NewAccount)
        self.pushButton_ConfigAccount = QtWidgets.QPushButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/button_icons/button_icons/pencil.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ConfigAccount.setIcon(icon1)
        self.pushButton_ConfigAccount.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_ConfigAccount.setObjectName("pushButton_ConfigAccount")
        self.verticalLayout.addWidget(self.pushButton_ConfigAccount)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_Home = QtWidgets.QPushButton(self.widget)
        self.pushButton_Home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Home.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/button_icons/button_icons/Home.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Home.setIcon(icon2)
        self.pushButton_Home.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.verticalLayout.addWidget(self.pushButton_Home)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addWidget(self.widget)
        self.tableWidget_Accounts = QtWidgets.QTableWidget(Form)
        self.tableWidget_Accounts.setObjectName("tableWidget_Accounts")
        self.tableWidget_Accounts.setColumnCount(0)
        self.tableWidget_Accounts.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tableWidget_Accounts)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_Accounts.setText(_translate("Form", "Accounts"))
        self.pushButton_NewAccount.setText(_translate("Form", " New Account"))
        self.pushButton_ConfigAccount.setText(_translate("Form", " Config Account"))
        self.pushButton_Home.setText(_translate("Form", "  Home "))
import icons_resource_file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
